### PR TITLE
bump: add AzureRM version 4 support

### LINKED ISSUE #77: [AVM Module Issue]: Support v4 of azurerm
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### (Optional) Correlation Id

_No response_

### Description

The versions of the providers are fixed (see in [required_providers](https://github.com/Azure/terraform-azurerm-avm-res-authorization-roleassignment/blob/0d5e7efe51445b2e9b296d4b396ca6b011baee34/terraform.tf#L6)) so we can't use this module with others because we can't use a newer version of a provider. According to the [Terraform doc](https://developer.hashicorp.com/terraform/language/modules/develop/providers#provider-aliases-within-modules):

> If you are writing a shared Terraform module, constrain only the minimum required provider version using a `>=` constraint. This should specify the minimum version containing the features your module relies on, and thus allow a user of your module to potentially select a newer provider version if other features are needed by other parts of their overall configuration.

Can you please change the constraint for each provider?

### PR DESCRIPTION
**Pull request by tobiasehlert**
## Description

Add support to AzureRM version 4.

Fixes #77

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [x] Azure Verified Module updates:
  - [x] Bugfix containing backwards compatible bug fixes
    - [x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates.
  - [ ] Breaking changes.
  - [x] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by tobiasehlert** [comment]
> Please add a test for v3. You can just copy one of the existing ones for now @tobiasehlert

hi @jaredfholgate, do you mean an example? I can't locate ant existing tests

**Comment by jaredfholgate** [comment]
> > Please add a test for v3. You can just copy one of the existing ones for now @tobiasehlert
> 
> hi @jaredfholgate, do you mean an example? I can't locate ant existing tests

Sorry, yes. Our examples are also run as end to end tests.

**Comment by tobiasehlert** [comment]
@jaredfholgate, now I've added an example called _basic-v3_ that uses `version = ">= 3.7, < 4.0"`.

**Review by jaredfholgate — APPROVED** [review]

**Comment by jaredfholgate** [comment]
Merging into a release branch so we can run the e2e tests.

**Comment by jaredfholgate** [comment]
#84

**Pull request merged**
